---
- name: Export Workflow
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../vault.yml"
  environment:
    CONTROLLER_HOST: aap.medina.vaultcrest.com/
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: password123!
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Export workflow job template
      ansible.controller.export:
        all: true
      register: export_results
      delegate_to: localhost

    - name: Show the results
      ansible.builtin.debug:
        var: export_results

    - name: Export workflow job template to file
      ansible.builtin.copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: /home/lab-user/casc_lab/workflow_export.yaml
...
