---
aap_organizations:
  - name: config_as_code
    galaxy_credentials:
      - hub_certified
      - hub_published
      - hub_community_infra_repo
      - hub_community
    default_environment: supported
...
