---
all:
  children:
    automationcontroller:
      hosts:
        control:
          ansible_host: "{{ 'controller.' + lookup('ansible.builtin.env', 'GUID') + '.sandbox####.opentlc.com' }}"
    execution:
      hosts:
        localhost:
          ansible_connection: local
...
